# These are supported funding model platforms

github: BlackBlazent # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2] 
open_collective: BlackBlazent # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: BlackBlazent # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: BlackBlazent
buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
thanks_dev: # Replace with a single thanks.dev username
patreon: lonestamp
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
- 'https://paypal.me/jednazlonestamp' 
