import { createClient } from "@supabase/supabase-js";

// ─── Supabase Client ──────────────────────────────────────────────────────────
// Vite exposes env vars via import.meta.env (not process.env)
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

const supabase = createClient(supabaseUrl, supabaseAnonKey);

// ─── Types ────────────────────────────────────────────────────────────────────

/** What the UI passes to the submission function */
export interface FeedbackPayload {
  /** 1–5 numeric rating (stored as integer, not star symbols) */
  rating: number;
  /** Optional free-text message from the user */
  message?: string;
}

/** Row shape that is inserted into the `user_feedback` table */
export interface UserFeedbackRow {
  id?: string;             // uuid, auto-generated by Supabase
  rating: number;          // integer 1–5
  message: string | null;  // nullable text
  submitted_at?: string;   // timestamptz, auto-set by default
}

/** Return value from submitFeedback() */
export interface SubmitFeedbackResult {
  success: boolean;
  data?: UserFeedbackRow;
  error?: string;
}

// ─── Validation ───────────────────────────────────────────────────────────────

function validatePayload(payload: FeedbackPayload): string | null {
  if (typeof payload.rating !== "number") return "Rating must be a number.";
  if (!Number.isInteger(payload.rating)) return "Rating must be a whole number.";
  if (payload.rating < 1 || payload.rating > 5) return "Rating must be between 1 and 5.";
  if (payload.message && payload.message.length > 1000) {
    return "Message must be 1000 characters or fewer.";
  }
  return null;
}

// ─── Core Submission Function ─────────────────────────────────────────────────

/**
 * Submits user feedback to the `user_feedback` Supabase table.
 *
 * - `rating`  → stored as an integer (1–5), NOT as star symbols
 * - `message` → stored as plain text (nullable)
 *
 * @example
 * const result = await submitFeedback({ rating: 4, message: "Great app!" });
 * if (result.success) console.log("Saved:", result.data);
 */
export async function submitFeedback(
  payload: FeedbackPayload
): Promise<SubmitFeedbackResult> {
  // 1. Validate input
  const validationError = validatePayload(payload);
  if (validationError) {
    return { success: false, error: validationError };
  }

  // 2. Build the row to insert
  //    rating  → integer (the numeric value of stars, e.g. 4)
  //    message → trimmed string or null
  const row: Omit<UserFeedbackRow, "id" | "submitted_at"> = {
    rating: payload.rating,
    message: payload.message?.trim() || null,
  };

  // 3. Insert into Supabase and return the created row
  const { data, error } = await supabase
    .from("user_feedback")
    .insert(row)
    .select()
    .single();

  if (error) {
    console.error("[submitFeedback] Supabase error:", error);
    return {
      success: false,
      error: "Failed to submit feedback. Please try again later.",
    };
  }

  return { success: true, data: data as UserFeedbackRow };
}

// ─── Optional: Fetch All Feedback (e.g. for an admin dashboard) ───────────────

export interface FetchFeedbackOptions {
  limit?: number;
  offset?: number;
  minRating?: number;
}

/**
 * Retrieves feedback rows from Supabase, newest first.
 * Useful for admin dashboards or analytics screens.
 */
export async function fetchFeedback(
  options: FetchFeedbackOptions = {}
): Promise<{ data: UserFeedbackRow[]; count: number | null; error?: string }> {
  const { limit = 20, offset = 0, minRating } = options;

  let query = supabase
    .from("user_feedback")
    .select("*", { count: "exact" })
    .order("submitted_at", { ascending: false })
    .range(offset, offset + limit - 1);

  if (minRating !== undefined) {
    query = query.gte("rating", minRating);
  }

  const { data, error, count } = await query;

  if (error) {
    console.error("[fetchFeedback] Supabase error:", error);
    return { data: [], count: null, error: "Failed to load feedback." };
  }

  return { data: (data as UserFeedbackRow[]) ?? [], count };
}